-- Generated by Oracle SQL Developer Data Modeler 18.4.0.339.1532
--   at:        2022-03-24 21:03:54 GMT
--   site:      SQL Server 2008
--   type:      SQL Server 2008



CREATE TABLE d_customer (
    "key"                NUMERIC(5) NOT NULL,
    id                   NUMERIC(5),
    name                 VARCHAR(50),
    age                  NUMERIC(3),
    segment              VARCHAR(50),
    region               VARCHAR(30),
    city                 VARCHAR(50),
    contact_name         VARCHAR(50),
    contact_title        VARCHAR(50),
    address              VARCHAR(50),
    postal_code          VARCHAR(15),
    phone                VARCHAR(30),
    fax                  VARCHAR(30),
    favorite_plataform   VARCHAR(50)
)

go

ALTER TABLE D_customer ADD constraint d_customer_pkv1 PRIMARY KEY CLUSTERED ("key")
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE d_customer add constraint d_customer_pk unique nonclustered ( "key" ) go

CREATE TABLE d_date 
    ( date_key NUMERIC(5) NOT NULL, 
     date DATE, day_week NUMERIC(1), day_month NUMERIC(2), date_description VARCHAR(40) 
    ) go

ALTER TABLE D_date ADD constraint d_date_pkv1 PRIMARY KEY CLUSTERED (date_key)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE d_date add constraint d_date_pk unique nonclustered ( date_key ) go

CREATE TABLE d_manufacturer (
    "key"           NUMERIC(8) NOT NULL,
    id              NUMERIC(8),
    company_name    VARCHAR(50),
    contact_title   VARCHAR(50),
    address         VARCHAR(50),
    city            VARCHAR(50),
    region          VARCHAR(50),
    postal_code     VARCHAR(50),
    country         VARCHAR(50),
    phone           VARCHAR(50),
    fax             VARCHAR(50)
)

go

ALTER TABLE D_Manufacturer ADD CONSTRAINT D_Manufacturer_PKv1 PRIMARY KEY CLUSTERED ("key")
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE D_Manufacturer ADD CONSTRAINT D_Manufacturer_PK UNIQUE NONCLUSTERED ("key")
GO

CREATE TABLE d_orders (
    "key"              NUMERIC(8) NOT NULL,
    id                 NUMERIC(8),
    order_date         datetime,
    required_date      datetime,
    shipped_date       datetime,
    freight            money,
    ship_name          VARCHAR(50),
    ship_address       VARCHAR(50),
    ship_city          VARCHAR(50),
    ship_region        VARCHAR(50),
    ship_postal_code   VARCHAR(50),
    ship_country       VARCHAR(50),
    currency_type      VARCHAR(20),
    quantity           SMALLINT,
    discount           REAL
)

go

ALTER TABLE D_Orders ADD constraint d_orders_pkv1 PRIMARY KEY CLUSTERED ("key")
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE d_orders add constraint d_orders_pk unique nonclustered ( "key" ) go

CREATE TABLE d_orders_internet (
    "key"              NUMERIC(8) NOT NULL,
    id                 NUMERIC(8),
    order_date         datetime,
    required_date      datetime,
    shipped_date       datetime,
    freight            money,
    ship_name          VARCHAR(50),
    ship_address       VARCHAR(50),
    ship_city          VARCHAR(50),
    ship_region        VARCHAR(50),
    ship_postal_code   VARCHAR(50),
    ship_country       VARCHAR(50),
    currency_type      VARCHAR(20),
    quantity           SMALLINT,
    discount           REAL
)

go

ALTER TABLE D_Orders_Internet ADD CONSTRAINT D_Orders_Internet_PKv1 PRIMARY KEY CLUSTERED ("key")
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE D_Orders_Internet ADD CONSTRAINT D_Orders_Internet_PK UNIQUE NONCLUSTERED ("key")
GO

CREATE TABLE d_product (
    "key"              NUMERIC(5) NOT NULL,
    id                 NUMERIC(5),
    name               VARCHAR(50),
    units_in_stock     NUMERIC(10),
    stock_max          NUMERIC(10),
    stock_min          NUMERIC(10),
    unit_price         money,
    units_on_order     NUMERIC(5),
    picture            image,
    description        ntext,
    origin_country     VARCHAR(50),
    biological_label   VARCHAR(50)
)

go

ALTER TABLE D_product ADD constraint d_product_pkv1 PRIMARY KEY CLUSTERED ("key")
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE d_product add constraint d_product_pk unique nonclustered ( "key" ) go

CREATE TABLE d_shippers (
    "key"          NUMERIC(8) NOT NULL,
    id             NUMERIC(8),
    contact_name   VARCHAR(50),
    company_name   VARCHAR(50),
    address        VARCHAR(50),
    city           VARCHAR(50),
    region         VARCHAR(50),
    postal_code    VARCHAR(50),
    country        VARCHAR(50),
    phone          VARCHAR(50),
    fax            VARCHAR(50)
)

go

ALTER TABLE D_Shippers ADD constraint d_shippers_pkv1 PRIMARY KEY CLUSTERED ("key")
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE d_shippers add constraint d_shippers_pk unique nonclustered ( "key" ) go

CREATE TABLE d_specialoffer (
    "key"              NUMERIC(8) NOT NULL,
    name               VARCHAR(50),
    description        VARCHAR(50),
    discount_product   smallmoney,
    type               VARCHAR(50),
    category           VARCHAR(50),
    start_date         datetime,
    end_date           datetime,
    min_qty            NUMERIC(10),
    max_qty            NUMERIC(10)
)

go

ALTER TABLE D_SpecialOffer ADD CONSTRAINT D_SpecialOffer_PKv1 PRIMARY KEY CLUSTERED ("key")
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE D_SpecialOffer ADD CONSTRAINT D_SpecialOffer_PK UNIQUE NONCLUSTERED ("key")
GO

CREATE TABLE d_store (
    "key"           NUMERIC(5) NOT NULL,
    id              NUMERIC(5),
    address         VARCHAR(50),
    city            VARCHAR(50),
    region          VARCHAR(50),
    district        VARCHAR(50),
    postal_code     VARCHAR(50),
    phone           VARCHAR(50),
    fax             VARCHAR(50),
    store_manager   VARCHAR(50),
    manager_id      NUMERIC(8),
    manager_name    VARCHAR(50)
)

go

ALTER TABLE D_store ADD constraint d_store_pkv1 PRIMARY KEY CLUSTERED ("key")
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE d_store add constraint d_store_pk unique nonclustered ( "key" ) go

CREATE TABLE d_suppliers (
    "key"          NUMERIC(8) NOT NULL,
    id             NUMERIC(8),
    contact_name   VARCHAR(50),
    company_name   VARCHAR(50),
    address        VARCHAR(50),
    city           VARCHAR(50),
    region         VARCHAR(50),
    postal_code    VARCHAR(50),
    country        VARCHAR(50),
    phone          VARCHAR(15),
    fax            VARCHAR(20)
)

go

ALTER TABLE D_Suppliers ADD constraint d_suppliers_pkv1 PRIMARY KEY CLUSTERED ("key")
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE d_suppliers add constraint d_suppliers_pk unique nonclustered ( "key" ) go

CREATE TABLE f_sale (
    product_key           NUMERIC(5) NOT NULL,
    store_key             NUMERIC(5) NOT NULL,
    specialoffer_key      NUMERIC(8) NOT NULL,
    manufacturer_key      NUMERIC(8) NOT NULL,
    date_key              NUMERIC(5) NOT NULL,
    shippers_key          NUMERIC(8) NOT NULL,
    suppliers_key         NUMERIC(8) NOT NULL,
    orders_key            NUMERIC(8) NOT NULL,
    orders_internet_key   NUMERIC(8) NOT NULL,
    customer_key          NUMERIC(5) NOT NULL,
    count_sales           NUMERIC(5),
    count_profits         NUMERIC(8),
    sale_campaings        NUMERIC(8)
)

go

ALTER TABLE F_sale ADD constraint f_sale_pk PRIMARY KEY CLUSTERED (product_key, store_key, SpecialOffer_key, Manufacturer_key, date_key, Shippers_key, Suppliers_key, Orders_key, customer_key, Orders_Internet_key)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON ) go

ALTER TABLE F_sale
    ADD CONSTRAINT f_sale_d_customer_fk FOREIGN KEY ( customer_key )
        REFERENCES d_customer ( "key" )
ON DELETE NO ACTION 
    ON UPDATE no action go

ALTER TABLE F_sale
    ADD CONSTRAINT f_sale_d_date_fk FOREIGN KEY ( date_key )
        REFERENCES d_date ( date_key )
ON DELETE NO ACTION 
    ON UPDATE no action go

ALTER TABLE F_sale
    ADD CONSTRAINT f_sale_d_manufacturer_fk FOREIGN KEY ( manufacturer_key )
        REFERENCES d_manufacturer ( "key" )
ON DELETE NO ACTION 
    ON UPDATE no action go

ALTER TABLE F_sale
    ADD CONSTRAINT f_sale_d_orders_fk FOREIGN KEY ( orders_key )
        REFERENCES d_orders ( "key" )
ON DELETE NO ACTION 
    ON UPDATE no action go

ALTER TABLE F_sale
    ADD CONSTRAINT f_sale_d_orders_internet_fk FOREIGN KEY ( orders_internet_key )
        REFERENCES d_orders_internet ( "key" )
ON DELETE NO ACTION 
    ON UPDATE no action go

ALTER TABLE F_sale
    ADD CONSTRAINT f_sale_d_product_fk FOREIGN KEY ( product_key )
        REFERENCES d_product ( "key" )
ON DELETE NO ACTION 
    ON UPDATE no action go

ALTER TABLE F_sale
    ADD CONSTRAINT f_sale_d_shippers_fk FOREIGN KEY ( shippers_key )
        REFERENCES d_shippers ( "key" )
ON DELETE NO ACTION 
    ON UPDATE no action go

ALTER TABLE F_sale
    ADD CONSTRAINT f_sale_d_specialoffer_fk FOREIGN KEY ( specialoffer_key )
        REFERENCES d_specialoffer ( "key" )
ON DELETE NO ACTION 
    ON UPDATE no action go

ALTER TABLE F_sale
    ADD CONSTRAINT f_sale_d_store_fk FOREIGN KEY ( store_key )
        REFERENCES d_store ( "key" )
ON DELETE NO ACTION 
    ON UPDATE no action go

ALTER TABLE F_sale
    ADD CONSTRAINT f_sale_d_suppliers_fk FOREIGN KEY ( suppliers_key )
        REFERENCES d_suppliers ( "key" )
ON DELETE NO ACTION 
    ON UPDATE no action go



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             31
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
